#!/bin/zsh

NAME="${0##*/}"
PROGRAM="${1:-MISSING}"
ARGS="${2:-MISSING}"
LOCATION="${$(realpath $2)%/*}"

ERR_MSG_MISSING_ARGUMENT="[$NAME][ERROR] Missing 1 or more arguments!\n\tArgument 1: $PROGRAM\n\tArgument 2: $ARGS"
MSG_NO_PERMISSION="[$NAME] You don't have permission to write to $LOCATION! Trying sudo...\n"

[[ -z "$2" ]] && { printf "$ERR_MSG_MISSING_ARGUMENT" && exit 1 }

[[ -f "$ARGS" ]] && SELECTION="$ARGS" || SELECTION="$LOCATION"

if [[ $(test -w "$SELECTION" ; echo $?) -eq 0 && $(test -r "$SELECTION" ; echo $?) -eq 0 ]]; then
    "$PROGRAM" "$ARGS"
else
    printf "$MSG_NO_PERMISSION"
    sleep 1
    sudo "$PROGRAM" "$ARGS"
fi
